# Generated by Django 2.0 on 2019-06-25 13:54

import apps.invoices.models
import apps.model_base
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apps.model_base.cutePk, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=64, null=True)),
                ('payee', models.CharField(blank=True, max_length=64, null=True)),
                ('key', models.CharField(default=apps.invoices.models.makeKey, max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('total_wei_due', models.DecimalField(decimal_places=0, max_digits=50)),
                ('min_payment_threshold', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
