# Generated by Django 2.0 on 2019-06-26 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='New', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='min_payment_threshold',
            field=models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
