# Generated by Django 2.0 on 2019-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20190626_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('published', 'Published'), ('partial_payment', 'Partial Payment'), ('paid_in_full', 'Paid in Full')], default='new', max_length=32),
        ),
    ]
