# Generated by Django 2.0 on 2019-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('published', 'Published'), ('agreed', 'Agreed'), ('partial_payment', 'Partial Payment'), ('paid_in_full', 'Paid in Full')], default='new', max_length=32),
        ),
    ]
