# Generated by Django 2.0 on 2019-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20190710_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_wei_due',
            new_name='invoice_amount_wei',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount_wei',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed')], default='new', max_length=32),
        ),
    ]
