# Generated by Django 2.0 on 2019-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20190711_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('published', 'Published'), ('agreed', 'Agreed'), ('partial_payment', 'Partial Payment'), ('paid_in_full', 'Paid in Full'), ('paused', 'Paused')], default='new', max_length=32),
        ),
    ]
