# Generated by Django 2.0 on 2019-09-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20190715_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('published', 'Published'), ('agreed', 'Agreed'), ('partial_payment', 'Partial Payment'), ('paid_in_full', 'Paid in Full')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
