# Generated by Django 2.0 on 2019-09-06 05:40

import apps.model_base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20190904_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.CharField(default=apps.model_base.cutePk, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price_in_wei', models.DecimalField(decimal_places=0, max_digits=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.Invoice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
