# Generated by Django 2.0 on 2019-09-16 07:54

import apps.model_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.CharField(default=apps.model_base.cutePk, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_address', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=64)),
                ('decimal_places', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
