version: '2.1'
services:
  psql:
    image: sameersbn/postgresql:9.6-2
    expose:
      - '5432'

    environment:
      DB_NAME: paywei
      DB_PASS: paywei
      DB_USER: paywei
    volumes:
      - /data/paywei/postgresql:/var/lib/postgresql

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    extends:
      service: paywei-django-dev
      file: build.yml
    volumes:
      - ../:/app
    links:
      - psql
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=django_shell
      - METRIC_ACCESS_KEY_ID=
      - METRIC_SECRET_ACCESS_KEY=
    command: "bash"
    entrypoint: []

  runserver:
    extends:
      service: paywei-django-dev
      file: build.yml
    command: ["python", "manage.py", "runserver_plus", "0.0.0.0:8000"]
    ports:
      - "9000:8000"
    links:
      - psql
    volumes:
      - ../:/app
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=runserver
      - METRIC_ACCESS_KEY_ID=
      - METRIC_SECRET_ACCESS_KEY=
